[display]
default_table_page_size = 10
default_table_max_columns = 50
cell_output = "above"
theme = "light"
default_width = "medium"
code_editor_font_size = 14
reference_highlighting = false
dataframes = "rich"

[language_servers.pylsp]
enable_pyflakes = false
enable_flake8 = false
enabled = true
enable_pylint = false
enable_mypy = true
enable_ruff = true
enable_pydocstyle = false

[language_servers.basedpyright]

[language_servers.ty]

[experimental]

[snippets]
custom_paths = []
include_default_snippets = true

[server]
browser = "default"
follow_symlink = false

[package_management]
manager = "pip"

[save]
autosave_delay = 1000
autosave = "off"
format_on_save = false

[ai]
mode = "manual"
rules = ""

[ai.models]
displayed_models = []
custom_models = []

[diagnostics]

[runtime]
default_auto_download = []
auto_reload = "autorun"
on_cell_change = "autorun"
std_stream_max_bytes = 1000000
default_sql_output = "auto"
output_max_bytes = 8000000
auto_instantiate = true
reactive_tests = true
watcher_on_save = "lazy"

[completion]
activate_on_typing = true
copilot = false

[keymap]
preset = "default"
destructive_delete = true

[keymap.overrides]

[formatting]
line_length = 79
