#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config layout bsp
yabai -m config focus_follows_mouse autoraise

yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.85

yabai -m config window_shadow float

# Mouse modifier key = fn. Move w/ left, resize w/ right
yabai -m config mouse_modifier ctrl
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# Automatically float non-resizable windows, such as palettes, system settings etc.

# Disable some applications to use yabai. In particular for apps not allowing for tiling...
# looking angrily at you macos
yabai -m config window_manager_check  off
yabai -m rule --add app=".*" float=on  # Float all windows by default
yabai -m rule --add app="^[Ss]ystem [Ss]ettings$" manage=off
yabai -m rule --add app="^[Cc]alculator$" manage=off
yabai -m rule --add app="^[Kk]arabiner-[Ee]lements$" manage=off
yabai -m rule --add app="^[Rr]aycast$" manage=off
yabai -m rule --add app="^[Kk]ee[Pp]ass[Xx][Cc]$" manage=off
yabai -m rule --add app="^[Cc]reative [Cc]loud$" manage=off
yabai -m rule --add app="^linearmouse$" manage=off
yabai -m rule --add app="^[Ll]ogi [Oo]ptions*$" manage=off
yabai -m rule --add app="^[Tt]oggl [Tt]rack$" manage=off
yabai -m rule --add app="^[Pp]rint [Cc]enter$" manage=off
yabai -m rule --add app="^[Ee]nte [Aa]uth$" manage=off
yabai -m rule --add app="^[fF]inder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add app="^[Aa]pp [Ss]tore$" manage=off
yabai -m rule --add app="^mpv$" manage=off
yabai -m rule --add app="^[Pp]ython$" manage=off
yabai -m rule --add app="[Mm]ac[Ww]hisper" manage=off
yabai -m rule --add app="[Pp]roton [Vv][Pp][Nn]" manage=off
yabai -m rule --add app="[Zz]otero" title="([Zz]ot[Ss]eek|[Pp]lugins [Mm]anager|[Zz]otero [Ss]ettings)" manage=off

# yabai -m signal --add event=window_created action='
#   yabai -m query --windows --window $yabai_window_id | jq -er ".\"can-resize\" or .\"is-floating\"" || \
#   yabai -m window $yabai_window_id --toggle float --layer above --grid 4:4:1:1:2:2
# '
