# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @treemux-tree-nvim-init-file "$HOME/.config/tmux/plugins/treemux/configs/treemux_init.lua"
set -g @plugin 'kiyoon/treemux'
set -g @plugin 'o0th/tmux-nova'
set -g mouse on

# Make hyperlink clickable (hold shift)
set -ga terminal-features "*:hyperlinks"

### NOVA
set -g @nova-nerdfonts true
set -g @nova-nerdfonts-left 
set -g @nova-nerdfonts-right 

set -g @nova-pane-active-border-style "#5DADE2"
set -g @nova-pane-border-style "#282a36"
set -g @nova-status-style-bg "#4c566a"
set -g @nova-status-style-fg "#d8dee9"
set -g @nova-status-style-active-bg "#89c0d0"
set -g @nova-status-style-active-fg "#2e3540"
set -g @nova-status-style-double-bg "#2d3540"

set -g @nova-pane "#I#{?pane_in_mode,  #{pane_mode},}  #W"

set -g @nova-segment-mode "#{?client_prefix,Ω,ω}"
set -g @nova-segment-mode-colors "#78a2c1 #2e3440"

set -g @nova-segment-whoami "#(whoami)@#H"
set -g @nova-segment-whoami-colors "#78a2c1 #2e3440"

set -g @cpu_percentage_format "%5.1f%%"
set -g @nova-segment-cpu " #($HOME/.config/tmux/plugins/tmux-cpu/scripts/cpu_percentage.sh)"
set -g @nova-segment-cpu-colors "#282a36 #f8f8f2"

set -g @cpu_temp_unit "C"
set -g @cpu_temp_format "%3.0f"
set -g @nova-segment-cpu-temp "#($HOME/.config/tmux/plugins/tmux-cpu/scripts/cpu_temp.sh)"
set -g @nova-segment-cpu-temp-colors "#282a36 #f8f8f2"

set -g @gpu_percentage_format "%5.1f%%"
set -g @nova-segment-gpu "󰘚 #($HOME/.config/tmux/plugins/tmux-cpu/scripts/gpu_percentage.sh)"
set -g @nova-segment-gpu-colors "#282a36 #f8f8f2"

set -g @gpu_temp_unit "C"
set -g @gpu_temp_format "%3.0f"
set -g @nova-segment-gpu-temp "#($HOME/.config/tmux/plugins/tmux-cpu/scripts/gpu_temp.sh)"
set -g @nova-segment-gpu-temp-colors "#282a36 #f8f8f2"

set -g @nova-segment-git-status '#(gitmux -cfg $HOME/.config/tmux/gitmux.conf "#{pane_current_path}")'

set -g @nova-rows 1
set -g @nova-segments-0-left "mode"
set -g @nova-segments-0-right "whoami"
set -g @nova-segments-1-left "cpu cpu-temp"
set -g @nova-segments-1-right "git-status gpu gpu-temp"
###

# Set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Open panes in current working directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# JUMPS WITH OPT AND COMMAND ON MACOS
bind -n M-Left send-keys 'M-b'  # Move left by word
bind -n M-Right send-keys 'M-f'  # Move right by word

# Set 256-color scheme (needed for e.g. nvim ig)
set -g default-terminal "screen-256color"
# tell Tmux that outside terminal supports true color
set -ga terminal-overrides ",xterm-256color*:Tc"

# Set the base index for windows to 1 instead of 0.
set -g base-index 1
setw -g pane-base-index 1

set -g pane-border-status top
set -g pane-border-format ' .#P (#D) #{pane_current_command} '

# Copy on select
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"

# Install tmux plugin manager if not installed yet
if "test ! -d $HOME/.config/tmux/plugins/tpm" \
  "run 'git clone https://github.com/tmux-plugins/tpm $HOME/.config/tmux/plugins/tpm && $HOME/.config/tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "$HOME/.config/tmux/plugins/tpm/tpm"

