set preview_images true
#set preview_images_method ueberzug
set use_preview_script false
set preview_script ~/.config/ranger/scope.sh
map yp shell -d echo -n %d/%f | xsel -i -p -b # Yank Path 
map yd shell -d echo -n %d | xsel -i -p -b    # Yank Dir
map yn shell -d echo -n %f | xsel -i -p -b    # Yank Name
