sub-font=Arial 
sub-scale=1
#vo=gpu-next 
#ao=pipewire 
#hwdec=nvdec # vaapi # change with AMD equivalent. 
hwdec-codecs=all 
#gpu-api=opengl 
#gpu-context=wayland # change this if not on Wayland. 
vd-lavc-dr=yes 
#vd-lavc-film-grain=gpu 
fullscreen=yes 
alang=ja,jp,jpn,en,eng,de,ger
slang=en,eng,de,ger
dither-depth=auto 
#dither=error-diffusion 
error-diffusion=sierra-lite
target-colorspace-hint=yes 
gamut-mapping-mode=auto 
target-peak=auto 
video-output-levels=full
volume-max=100
scale=ewa_lanczossharp
cscale=ewa_lanczossoft
dscale=mitchell
scale-antiring=0.7
cscale-antiring=0.7
dither-depth=auto
correct-downscaling=yes
sigmoid-upscaling=yes
deband=no
demuxer-mkv-subtitle-preroll=yes
tone-mapping=auto 
#tone-mapping=reinhard
#tone-mapping-param=0.6

