[ids]
*

[main]
shift = oneshot(shift)
control = oneshot(control)
leftalt = oneshot(alt)
rightalt = oneshot(altgr)

insert = S-insert

capslock = overload(control, enter)

[altgr]
n = ñ

[shift+altgr]
n = Ñ

