#!/usr/bin/env zsh

findsamemodel() {
  local ref="$1" dir="$2" name="${3:-model.zip}"
  local refhash
  refhash=$(unzip -p "$ref" policy.pth | md5sum | awk '{print $1}')
  find "$dir" -type f -name "$name" -print0 | while IFS= read -r -d '' f; do
    [[ "$(unzip -p "$f" policy.pth 2>/dev/null | md5sum | awk '{print $1}')" == "$refhash" ]] \
      && print -r -- "${f:A}"
  done
}
