#!/usr/bin/env zsh

nm() {
  NVIM_QUIT_ON_LAST=1 nvim \
    --cmd "let g:auto_session_enabled = v:false" \
    -c "NmSearch ${(q)@}" \
    -c "autocmd VimEnter * ++once if bufexists(1) && bufnr('%') != 1 | silent! bwipeout 1 | endif"
}
