live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#4D5566"
blue = "#59C2FF"
cyan = "#95E6CB"
green = "#56DB3A"
magenta = "#FFEE99"
red = "#FF3333"
white = "#B3B1AD"
yellow = "#FF8F40"

[colors.normal]
black = "#0a0e14"
blue = "#73d0ff"
cyan = "#95e6cb"
green = "#BAE67E"
magenta = "#d4bfff"
red = "#ff3333"
white = "#cbccc6"
yellow = "#C19C00"

[colors.primary]
background = "#0A0E14"
foreground = "#B3B1AD"

[cursor.style]
blinking = "Off"
shape = "Underline"

[env]
TERM = "xterm-256color"
PATH = "/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin"
# XDG_CONFIG_HOME = "/Users/joshua/.config"

[font]
builtin_box_drawing = false
size = 11.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 4

[window]
# decorations = "transparent"
dynamic_title = true
opacity = 1.0
resize_increments = false

[window.padding]
x = 4
y = 8

[window.class]
general = "Alacritty"
instance = "Alacritty"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
  # { key = "Right", mods = "Command", chars = "\u001b[F" },- 
  { key = "A", mods = "Command", chars = "\u0001" },
  { key = "K", mods = "Alt", chars = "\u001bk" },
  { key = "J", mods = "Alt", chars = "\u001bj" },
  { key = "H", mods = "Alt", chars = "\u001bh" },
  { key = "L", mods = "Alt", chars = "\u001bl" },
  #{ key = "Left", mods = "Alt", chars = "\u001bh" },
  #{ key = "Right", mods = "Alt", chars = "\u001bl" }
  # { key = "Left", mods = "Command", action = "Move", chars = "BeginningOfLines" },
]

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-D", "-s", "main", "-f", "/Users/joshua/.config/tmux/tmux.conf"]

#[shell]
#program = "/bin/zsh"
#args = ["-c", "/opt/homebrew/bin/tmux"]

#[shell]
#program = "/bin/zsh"
#args = ["-c", "env > ~/alacritty_env.txt && /opt/homebrew/bin/tmux"]
#[shell]
#program = "/bin/zsh"
#args = ["-c", "source ~/.zshrc && tmux"]

