#!/usr/bin/env bash

### VERY FIRST THING: DECRYPT KEYS
export $(sops --decrypt ~/dotfiles/secrets.env | xargs)

# Path to your oh-my-zsh installation.
export XDG_CONFIG_HOME="$HOME/.config"
export ZSH="$XDG_CONFIG_HOME/zsh/oh-my-zsh"
export ZSHRC="$XDG_CONFIG_HOME/zsh/.zshrc"
export OMPY="$XDG_CONFIG_HOME/oh-my-posh/.mytheme.omp.yaml"
export BOOKMARKS="$XDG_CONFIG_HOME/zsh/.zsh_hashes"

export WANDB_MODE='online'

DISABLE_LS_COLORS='true'

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export SN_USE_SESSION=yes

### Sort "*2.smth" before "*10.smth"
setopt numericglobsort

# Because ZSH did not take into account custom prompt functions we need to disable async loading
zstyle ':omz:alpha:lib:git' async-prompt no
zstyle ':completion:*' menu select
zstyle ':completion:*' group-name ''
zstyle ':completion:*' completer _extensions _complete _approximate
zstyle ':completion:*:*:*:*:descriptions' format '%F{green}-- %d --%f'
zstyle ':completion:*:warnings' format ' %F{red}-- no matches found --%f'
ZSH_THEME='customized-bira'

# Use fd (https://github.com/sharkdp/fd) for listing path candidates.
# - The first argument to the function ($1) is the base path to start traversal
# - See the source code (completion.{bash,zsh}) for the details.
_fzf_compgen_path() {
  fd --hidden --follow --exclude ".git" . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --type d --hidden --follow --exclude '.git' . "$1"
}

fzf-home-widget() {
  local file
  file=$(cd ~ && fd --type f --hidden --follow --exclude '.git' . | fzf)
  [[ -n $file ]] && LBUFFER+="$HOME/$file"
  zle redisplay
}

zle -N fzf-home-widget
bindkey '^[t' fzf-home-widget # Alt-T

# CASE_SENSITIVE='true'    # a == A ?
HYPHEN_INSENSITIVE='true' # - == _ ?

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION='true'

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS='true'

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY='true'

### HISTORY FILE
export HISTFILE=$XDG_CONFIG_HOME/zsh/zsh_history
HIST_STAMPS='yyyy-mm-dd'
export HISTSIZE=10000000
export SAVEHIST=$HISTSIZE
setopt extendedhistory

export FZF_BASE=/usr/bin/fzf
export FZF_DEFAULT_OPTS='--height 40% --tmux center,60%'
DISABLE_FZF_KEY_BINDINGS='false'

### PLUGINS
plugins=(
  # git # With tmux, we do not really need this
  z # Easy fuzzy navigation
  # vscode  # cmd shortcuts. E.g.: `vscd f1 f2` opens diff in code
  sudo # Double escape sudo's last command
  #dirhistory
  #history
  # copybuffer
  zsh-autosuggestions
  # virtualenv
  fzf
  mise
)

FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

source $ZSH/oh-my-zsh.sh

### User configuration

### MACROS
export MANPAGER='nvim +Man!'

### GEMINI
export GEMINI_SANDBOX=true

### DEFAULT EDITOR
export VISUAL=nvim
export EDITOR="$VISUAL"
export VIMTEX_OUTPUT_DIRECTORY='out'

### CUSTOM COMPOSE FILE
export XCOMPOSEFILE='$XDG_CONFIG_HOME/XCompose'

### PAGER (LESS) CONFIG
export PAGER='less -r'
export LESS='--mouse --wheel-lines 4'
export LESSHISTFILE=$XDG_CONFIG_HOME/.lesshst

### DOCKER
#export DOCKER_DEFAULT_PLATFORM='linux/amd64'
alias ssh_tb='ssh -L 16006:127.0.0.1:6006'
alias ssh_mo='ssh -L 12718:127.0.0.1:2718'
alias rt='trash'

### HELPFUL ALIASES
alias cwd=pwd
alias dnfi='sudo dnf install'
alias dnfu='sudo dnf update'
alias dnfua='sudo dnf update --refresh'
alias brewua='brew update && brew upgrade && brew upgrade --cask && brew cleanup'
alias n='nvim'
alias n.='nvim .'
alias v='nvim'
alias v.='nvim .'
alias pdf='zathura'
alias bt='btop'

alias m='mise'
alias mx='mise exec'
alias mp='mise prepare'
alias mu='mise use'
alias mup='mise upgrade'
alias mr='mise run'

if [[ ! "${OSTYPE}" == 'darwin'* ]]; then
  alias c='xclip -sel c -r'
else
  alias c='pbcopy'
fi

# Directory aliases
alias ols='/bin/ls -l'
alias ls='lsd'
alias l='lsd -l'
alias ll='lsd -la'
alias la='lsd -lA'
alias lt='lsd --tree'
alias llt='lsd -a --tree'
alias lat='lsd -la --tree'
alias llat='lsd -la --tree'
alias pwdy="echo $(pwd) | pbcopy" # Copy current directory to clipboard
#alias cd='z'

alias lg='lazygit'
alias jless='jless --line-numbers --relative-line-numbers'
alias jl='jless'

# Obsidian
export O_VAULT_DIR="$HOME/vaults/obsidian-notes"
alias oo='cd $O_VAULT_DIR'
alias or='nvim $O_VAULT_DIR/inbox/*.md'
alias nvl="nvim --listen 127.0.0.1:2006"

# Time tracking via toggl track python cli (https://github.com/AuHau/toggl-cli)
alias tt='toggl start'
alias ttw='toggl start "Uncategorized Meeting (Daily, NEXD Weekly, ...)"'
alias ttws='toggl start -o Service "Service Meeting (Gruppenseminar, CAKE, MOSI Weekly, ...)"'
alias tts='toggl start -o Service'
alias ttm='toggl start -o Main'
alias ttd='toggl start -o Side'
alias ttt='toggl stop'
alias ttl='toggl ls -f+id'
alias ttr='toggl rm'

# Copy directory over ssh
alias rcp='rsync -saLPz --port 22 -e ssh '
alias rcps='rsync -saLPz --port 22 --chmod=F600,D700 -e ssh '

# Custom git aliases for submodules
alias gsua='git submodule update --remote --recursive && git add . && git commit -m "Update Submodules to latest remote version" -e'
alias gsp='git push --recurse-submodules=on-demand'
alias gs='git status'
alias gl="git log --all --graph --pretty=format:'%C(magenta)%h %C(white) %an %ar%C(auto)  %D%n%s%n'"
alias gd='git ddiff'

# Custom jj aliases
alias jjs='jj st'
alias jja='jj abandon'
alias jjbmm='jj bookmark move main --to @-'
alias jjgp='jj git push'
alias jjp='jj prev'
alias jjn='jj next'
alias jjc='jj new'
alias jjl='jj log'
alias jjd='jj describe'
alias jjdf='jj diff'
alias jjt='jj track'
alias jju='jj undo'
alias jjut='jj untrack'
alias neogit="nvim +\"lua vim.defer_fn(function() require('neogit').open() end, 0)\""
alias ng='neogit'
alias dt='difft'

# Always start ipython with current venv
alias ipy="python -c 'import IPython; IPython.terminal.ipapp.launch_new_instance()'"
alias univpn='sudo openconnect vpn.hiz-saarland.de --authgroup UdS -u s8jjmeye '
alias nonzero_mean="grep -rnPo ' \"mean\": (?!0\.0\b,)[0-9]+(?:\.[0-9]+)?'"

# Start obsidian (flatpak installation) manually to allow for gpg-signing
if [[ ! "$OSTYPE" == 'darwin'* ]]; then
  alias obsidian='/var/lib/flatpak/app/md.obsidian.Obsidian/current/active/files/obsidian'
fi

# suffix aliases
alias -s md='bat'
alias -s png='open'
alias -s jpg='open'
alias -s jpeg='open'
alias -s pdf='open'
alias -s mp4='open'
alias -s mov='open'
alias -s js="$EDITOR"
alias -s ts="$EDITOR"
alias -s yaml='jless --yaml'
alias -s yml='jless --yaml'
alias -s json='jless'
alias -s jsonl='jless'

# global aliases
alias -g NE='2>/dev/null'     # Ignore stderr
alias -g ND='>/dev/null'      # Ignore stdout
alias -g NUL='>/dev/null 2>1' # Ignore both stdout and stderr
alias -g L='| less'           # Pipe to less with raw control chars
alias -g WC='| wc -w'         # word count
alias -g WCL='| wc -l'        # word count

if [[ ! "$OSTYPE" == 'darwin'* ]]; then
  alias -g C='| xclip -sel c -r'
else
  alias -g C='| pbcopy'
fi

# Load hash aliases
if [[ -f ${XDG_CONFIG_HOME}/zsh/.zsh_hashes ]]; then
  source ${XDG_CONFIG_HOME}/zsh/.zsh_hashes
fi

### AUTOLAODS
# Autoload custom zsh functions
fpath=($XDG_CONFIG_HOME/zsh/functions $fpath)
autoload -U jview
autoload -U _jview
compdef _jview jview

autoload -U _toggl
autoload -U check_git_dirty

autoload -U mcd
autoload -U mvln
# Autoload deepl functions
autoload -U dtj
autoload -U dts
autoload -U std
autoload -U td
autoload -U te
autoload -U tj
autoload -U ts
autoload -U lkey_nojq

### HANDY KEYBINDS
copy-command() {
  echo -n $BUFFER | pbcopy
  zle -M 'Copied to clipboard'
}
zle -N copy-command

bindkey '^K' kill-line
bindkey '^[^?' backward-kill-line
bindkey '^W' backward-kill-word
bindkey '^F' autosuggest-accept
bindkey '^Xc' copy-command

### TMUX custom function
function tmuxsc() {
  local session_name="$1"

  if tmux has-session -t "$session_name" 2>/dev/null; then
    # If the session exists, switch to it
  else
    # If the session doesn't exist, create it in detached mode and switch to it
    tmux new-session -d -s "$session_name"
  fi
  tmux switch-client -t "$session_name"
}

### yazi
# function y() {
# 	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
# 	yazi "$@" --cwd-file="$tmp"
# 	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
# 		builtin cd -- "$cwd"
# 	fi
# 	rm -f -- "$tmp"
# }

# Detect source and translate to

### LOCAL BINARY DIR
export PATH="$HOME/.local/bin:$PATH"

### GO BINARIES
export PATH="$HOME/go/bin:$PATH"

### Add homebrew to path, but APPEND
export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar"
export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew"
export PATH="${PATH}:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin"
export MANPATH="/home/linuxbrew/.linuxbrew/share/man${MANPATH+:$MANPATH}:"
export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:${INFOPATH:-}"

### CUDA
#export CUDA_HOME="/usr/local/cuda"
#export PATH="${PATH}:${CUDA_HOME}/bin"
#export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+${LD_LIBRARY_PATH}:}${CUDA_HOME}/lib64:/usr/lib64"
#export LIBRARY_PATH="${LIBRARY_PATH:+${LIBRARY_PATH}:}${LD_LIBRARY_PATH}"

eval "$(oh-my-posh init zsh --config "${HOME}/.config/oh-my-posh/.mytheme.omp.yaml")"

if [[ "$OSTYPE" == "darwin"* ]]; then
  ### Tev wrapper for macos... Seems to try and execute x86 instead of arm64 otherwise...
  alias tev="arch -arm64 /Applications/tev.app/Contents/MacOS/tev"
  alias anki="/Applications/Anki.app/Contents/MacOS/launcher ; exit;"
  export PATH="${PATH}:/opt/homebrew/opt/coreutils/libexec/gnubin"
fi

# Load custom LS colors
source $XDG_CONFIG_HOME/zsh/lscolors.sh

### CUSTOM ZSH PROMPT

# precmd_prompt () {
#   # Regex to find visible character length of prompt string
#   local zero='%([BSUbfksu]|([FK]|){*})'
#
#   # split left part of first line
#   local left_pref='─%B%(!.%{%}.%{%})%n@%m%{%} %B%{%}%4~ %{%}'
#   left_eval=$(ruby_prompt_info)$(venv_info) # $(git_prompt_info)$(hg_prompt_info)
#
#   # Define what should be shown on the right
#   PS1_1_right=${(%):-'[%D{%H:%M:%S}] '}
#
#   # Git Prompt. Currently placed on the right. Could also be placed in the middle maybe? Will see
#   local vcs_branch=$(git_prompt_info)$(hg_prompt_info)
#
#   # Compute length of the left prompt
#   local left_pref_length=${#${(S%%)left_pref//$~zero/}}
#   local left_length=${#${(S%%)left_eval//$~zero/}}
#   left_length=$(($left_length+$left_pref_length+2))
#
#   # Compute length of the git prompt
#   local git_length=${#${(S%%)vcs_branch//$~zero/}}
#
#   # Compute the necessary width for the middle prompt.
#   local middle_width=$((COLUMNS-left_length-${#PS1_1_right}-git_length))
#
#   # Fill middle up to necessary length with spaces
#   PS1_1_middle=${(r:$middle_width:: :)}
#
#   # Finally build the prompt. First line right prompt color hard coded because of length calculation.
#   ### GIT ON RIGHT
#   PROMPT="${PROMPT_FL}${PS1_1_middle}${vcs_branch}%{$fg[green]%}${PS1_1_right}%{$reset_color%}"$'\n'"${PROMPT_SL}"
#   ### GIT ON LEFT
#   # PROMPT="${PROMPT_FL}${vcs_branch}${PS1_1_middle}%{$fg[green]%}${PS1_1_right}%{$reset_color%}"$'\n'"${PROMPT_SL}"
#   ### GIT IN MIDDLE? Should be possible, but idk if better
# }
#precmd_functions+=(precmd_prompt)

### FOR JEKYLL/RUBY
# chruby for ruby env
# source $(brew --prefix)/opt/chruby/share/chruby/chruby.sh
# source $(brew --prefix)/opt/chruby/share/chruby/auto.sh
# Change away from system ruby
# chruby ruby-3.3.5

### FOR MUJOCO_PY
#export PATH="/opt/homebrew/opt/llvm/bin:$PATH"

#export CC="/opt/homebrew/opt/llvm/bin/clang"
#export CXX="/opt/homebrew/opt/llvm/bin/clang++"
#export CXX11="/opt/homebrew/opt/llvm/bin/clang++"
#export CXX14="/opt/homebrew/opt/llvm/bin/clang++"
#export CXX17="/opt/homebrew/opt/llvm/bin/clang++"
#export CXX1X="/opt/homebrew/opt/llvm/bin/clang++"

#export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
#export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"

# export NVM_DIR="$HOME/.nvm"
#   [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
#   [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"

# Added by LM Studio CLI (lms)
export PATH="$PATH:$HOME/.cache/lm-studio/bin"
export GOOGLE_CLOUD_PROJECT="see-far"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

#compdef toggl
# eval is used to hide the Zsh-specific ${(%):-%x} syntax from shfmt
eval 'current_script="${(%):-%x}"'

if [[ "$(basename -- "$current_script")" != "_toggl" ]]; then
  compdef _toggl toggl
fi

# Android Studio and SDK
# export ANDROID_HOME=$HOME/Library/Android/sdk
# export PATH=$PATH:$ANDROID_HOME/platform-tools
# export PATH=$PATH:$ANDROID_HOME/tools
# export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home

if [[ "$OSTYPE" == "darwin"* ]]; then
  # Use GNU tools instead of BSD tools on macOS
  export PATH="$HOME/.local/gnubin:$PATH"
fi

###### THE FOLLOWING SHOULD BE AT THE END.
eval "$(mise activate zsh)"
### Make sure homebrew is the first to be looked up
#export PATH="/opt/homebrew/bin:$PATH"
### Apply all defined hooks, e.g., sourcing .source_me files.
# load-local-conf
