#!/usr/bin/env bash

### EXPORTS
# All exports are in exports.zsh
export XDG_CONFIG_HOME="$HOME/.config"
source ${XDG_CONFIG_HOME}/zsh/exports.zsh

### Sort "*2.smth" before "*10.smth"
setopt numericglobsort
setopt extendedhistory

# Because ZSH did not take into account custom prompt functions we need to disable async loading
zstyle ':omz:alpha:lib:git' async-prompt no
zstyle ':completion:*' menu select
zstyle ':completion:*' group-name ''
zstyle ':completion:*' completer _extensions _complete _approximate
zstyle ':completion:*:*:*:*:descriptions' format '%F{green}-- %d --%f'
zstyle ':completion:*:warnings' format ' %F{red}-- no matches found --%f'

ZSH_THEME='customized-bira'

# CASE_SENSITIVE='true'    # a == A ?
HYPHEN_INSENSITIVE='true' # - == _ ?

DISABLE_FZF_KEY_BINDINGS='false'

### PLUGINS
plugins=(
  z    # Easy fuzzy navigation
  sudo # Double escape sudo's last command
  zsh-autosuggestions
  fzf
  mise
)

FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
source ${ZSH}/oh-my-zsh.sh

### User configuration
[ -f ${XDG_CONFIG_HOME}/zsh/functions.zsh ] && source ${XDG_CONFIG_HOME}/zsh/functions.zsh
[ -f ${XDG_CONFIG_HOME}/zsh/.zsh_aliases ] && source ${XDG_CONFIG_HOME}/zsh/.zsh_aliases
[ -f ${XDG_CONFIG_HOME}/zsh/.zsh_hashes ] && source ${XDG_CONFIG_HOME}/zsh/.zsh_hashes

### AUTOLOADS
# Add custom functions path to fpath and autoload all functions within
if [[ -d ${XDG_CONFIG_HOME}/zsh/functions ]]; then
  FPATH="${XDG_CONFIG_HOME}/zsh/functions:${FPATH}"
  for func_file in ${XDG_CONFIG_HOME}/zsh/functions/*; do
    [ -f "${func_file}" ] && autoload -U ${func_file:t}
  done
fi

# Completion definitions
compdef _jview jview
if [[ "$(basename -- "$current_script")" != "_toggl" ]]; then
  compdef _toggl toggl
fi

### HANDY KEYBINDS
bindkey '^K' kill-line
bindkey '^[^?' backward-kill-line
bindkey '^W' backward-kill-word
bindkey '^F' autosuggest-accept

eval "$(oh-my-posh init zsh --config "${XDG_CONFIG_HOME}/oh-my-posh/.mytheme.omp.yaml")"

# Load custom LS colors
[ -f ${XDG_CONFIG_HOME}/zsh/lscolors.sh ] && source ${XDG_CONFIG_HOME}/zsh/lscolors.sh
[ -f ${HOME}/.fzf.zsh ] && source ${HOME}/.fzf.zsh

# eval is used to hide the Zsh-specific ${(%):-%x} syntax from shfmt
eval 'current_script="${(%):-%x}"'

###### THE FOLLOWING SHOULD BE AT THE END.
eval "$(mise activate zsh)"

### Apply all defined hooks, e.g., sourcing .source_me files.
# load-local-conf

################################################################################

### [LEGACY] CUSTOM ZSH PROMPT

# precmd_prompt () {
#   # Regex to find visible character length of prompt string
#   local zero='%([BSUbfksu]|([FK]|){*})'
#
#   # split left part of first line
#   local left_pref='─%B%(!.%{%}.%{%})%n@%m%{%} %B%{%}%4~ %{%}'
#   left_eval=$(ruby_prompt_info)$(venv_info) # $(git_prompt_info)$(hg_prompt_info)
#
#   # Define what should be shown on the right
#   PS1_1_right=${(%):-'[%D{%H:%M:%S}] '}
#
#   # Git Prompt. Currently placed on the right. Could also be placed in the middle maybe? Will see
#   local vcs_branch=$(git_prompt_info)$(hg_prompt_info)
#
#   # Compute length of the left prompt
#   local left_pref_length=${#${(S%%)left_pref//$~zero/}}
#   local left_length=${#${(S%%)left_eval//$~zero/}}
#   left_length=$(($left_length+$left_pref_length+2))
#
#   # Compute length of the git prompt
#   local git_length=${#${(S%%)vcs_branch//$~zero/}}
#
#   # Compute the necessary width for the middle prompt.
#   local middle_width=$((COLUMNS-left_length-${#PS1_1_right}-git_length))
#
#   # Fill middle up to necessary length with spaces
#   PS1_1_middle=${(r:$middle_width:: :)}
#
#   # Finally build the prompt. First line right prompt color hard coded because of length calculation.
#   ### GIT ON RIGHT
#   PROMPT="${PROMPT_FL}${PS1_1_middle}${vcs_branch}%{$fg[green]%}${PS1_1_right}%{$reset_color%}"$'\n'"${PROMPT_SL}"
#   ### GIT ON LEFT
#   # PROMPT="${PROMPT_FL}${vcs_branch}${PS1_1_middle}%{$fg[green]%}${PS1_1_right}%{$reset_color%}"$'\n'"${PROMPT_SL}"
#   ### GIT IN MIDDLE? Should be possible, but idk if better
# }
#precmd_functions+=(precmd_prompt)
